# Generated by Django 4.1.4 on 2022-12-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('littera', models.CharField(max_length=2, verbose_name='Буква класса')),
                ('number_of_grade', models.PositiveIntegerField(verbose_name='Номер класса')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
                'ordering': ['number_of_grade'],
            },
        ),
    ]
