# Generated by Django 4.1.4 on 2022-12-09 08:11

from django.db import migrations, models
import teacher.utils


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0003_alter_student_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='littera',
            field=models.CharField(max_length=1, verbose_name='Буква класса'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='number_of_grade',
            field=models.PositiveIntegerField(validators=[teacher.utils.validate_grade], verbose_name='Номер класса'),
        ),
    ]
