# Generated by Django 4.1.4 on 2022-12-09 06:16

import director.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headteacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=55)),
                ('last_name', models.CharField(max_length=55)),
                ('third_name', models.CharField(max_length=55)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Head_teacher/')),
                ('phone', models.CharField(help_text='введите свои данные.', max_length=12, unique=True, validators=[director.utils.validate_phone_number])),
            ],
            options={
                'verbose_name': 'завуч',
                'verbose_name_plural': 'завучи',
                'ordering': ['first_name'],
            },
        ),
    ]
